name: Node.js CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Build
      run: yarn run build
